 Numpy 배열은 기본 자료구조로 ndarray라는 배열을 사용한다. ndarray의 기본 속성은 다음과 같다.
 * ndim: 차원의 수
 * shape: 각 차원의 크기(튜플)
 * size: 전체 요소의 수
 * dtype: 요소의 데이터 타입
 * itemsize: 각 요소의 바이트 크기

In [2]:
import cv2
img = cv2.imread('img/jiheon.jpg')
print(type(img))

<class 'numpy.ndarray'>


In [2]:
print(img.ndim)

3


In [3]:
print(img.shape)

(846, 564, 3)


In [14]:
print(img.size)
print(img.dtype)
print(img.itemsize)

1431432
uint8
1


In [4]:
import numpy as np
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [5]:
a.dtype

dtype('int32')

In [6]:
type(a)

numpy.ndarray

In [8]:
a[0].dtype

dtype('int32')

In [7]:
b = np.array([[1,2,3,4], [5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
b.shape

(2, 4)

In [10]:
c = np.array([[1],[2],[3],[4]])
c

array([[1],
       [2],
       [3],
       [4]])

In [11]:
c.shape

(4, 1)

In [12]:
c.dtype

dtype('int32')

In [4]:
import numpy as np

In [15]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [17]:
a.dtype

dtype('int32')

In [18]:
a.shape

(4,)

In [19]:
a = np.array([1.1,2,3,4])
a

array([1.1, 2. , 3. , 4. ])

In [20]:
a.dtype

dtype('float64')

In [27]:
a = np.uint8([1,2,3,4])
b = np.int32([1.8,2,3,4])
a, b

(array([1, 2, 3, 4], dtype=uint8), array([1, 2, 3, 4]))

* numpy.empty(shape, [, dtype])  # 초기화 안됨
* numpy.zeros(shape, [, dtype])  # 0으로 초기화
* numpy.ones(shape, [, dtype])  # 1로 초기화
* numpy.full(shape, fill_value, [, dtype])  # fill_value로 초기화

In [28]:
a = np.empty((2,3)) # [[ , , ], [ , , ]]
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
b = np.zeros((2,3)) # [[0,0,0], [0,0,0]]
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
c = np.ones((2,3)) # [[1,1,1], [1,1,1]]
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [31]:
d = np.full((2,3), 255) # [[255,255,255], [255,255,255]]
d

array([[255, 255, 255],
       [255, 255, 255]])

In [32]:
b.dtype

dtype('float64')

In [33]:
e = np.zeros((2,3), dtype='uint16')
e

array([[0, 0, 0],
       [0, 0, 0]], dtype=uint16)

In [34]:
img

array([[[126, 144, 167],
        [163, 181, 204],
        [142, 159, 180],
        ...,
        [160, 169, 183],
        [160, 169, 183],
        [160, 169, 183]],

       [[172, 188, 211],
        [129, 146, 167],
        [145, 162, 183],
        ...,
        [160, 169, 183],
        [160, 169, 183],
        [160, 169, 183]],

       [[147, 161, 183],
        [133, 148, 167],
        [162, 177, 196],
        ...,
        [160, 169, 183],
        [160, 169, 183],
        [160, 169, 183]],

       ...,

       [[127,  90,  38],
        [126,  89,  37],
        [129,  90,  38],
        ...,
        [181, 175, 210],
        [176, 170, 205],
        [174, 168, 203]],

       [[135,  92,  35],
        [133,  90,  33],
        [133,  89,  35],
        ...,
        [180, 174, 209],
        [176, 170, 205],
        [174, 168, 203]],

       [[140,  94,  36],
        [137,  91,  33],
        [136,  89,  33],
        ...,
        [180, 174, 209],
        [175, 169, 204],
        [173, 167, 202]]

In [35]:
img.shape

(846, 564, 3)

In [36]:
a = np.empty_like(img)
a

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [38]:
a.shape

(846, 564, 3)

In [39]:
a.fill(0)
a

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [40]:
b = np.zeros_like(img)
b

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [44]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
a.fill(1)
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [54]:
t = np.empty_like(a)
t

array([[1., 1., 1.],
       [1., 1., 1.]])

In [55]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [60]:
b = np.arange(5.0, 10.0, 1.0)
b

array([5., 6., 7., 8., 9.])

In [61]:
c = np.arange(10, 20, 2)
c

array([10, 12, 14, 16, 18])

In [63]:
d = np.random.rand(2,3)
d

array([[0.24436792, 0.2006526 , 0.99935695],
       [0.22720088, 0.6001561 , 0.75342399]])

In [64]:
e = np.random.randn(2,3)
e

array([[-0.2220089 , -0.50469252,  0.79119021],
       [ 0.04145339,  0.5184438 ,  2.15480091]])

In [73]:
a = np.random.rand(1)
a

array([0.76528529])

In [74]:
f = np.random.randint(0, 10, (3,3))
f

array([[8, 8, 5],
       [0, 2, 5],
       [1, 8, 3]])

In [75]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [76]:
b = a.astype(np.float64)
b

array([0., 1., 2., 3., 4.])

In [77]:
c = np.uint8(a)
c

array([0, 1, 2, 3, 4], dtype=uint8)

In [78]:
a.shape # 1차원의 경우 이렇게 표기

(5,)

In [79]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [80]:
b = a.reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [81]:
c = np.reshape(a, (2,3))
c

array([[0, 1, 2],
       [3, 4, 5]])

In [82]:
d = np.arange(100)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [83]:
e = d.reshape(2, -1) # 하나면 쓰고 -1로 넣으면 나머지는 알아서 계산해준다
e

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [84]:
f = d.reshape(-1, 5)
f

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [108]:
b = np.empty_like(a, np.uint8)
b

array([[1, 1, 1],
       [1, 1, 1]], dtype=uint8)

In [87]:
a = np.reshape(np.arange(6), (2,3))
a

array([[0, 1, 2],
       [3, 4, 5]])

In [88]:
b = np.ravel(a)
b

array([0, 1, 2, 3, 4, 5])

In [89]:
b = a.reshape((6,))
b

array([0, 1, 2, 3, 4, 5])

In [92]:
c = a.reshape(-1,)
c

array([0, 1, 2, 3, 4, 5])

In [93]:
d = np.ravel(a)
d

array([0, 1, 2, 3, 4, 5])

In [94]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [112]:
b= a.T # 전치행렬 구하기
a, b

(array([[254,  36, 191],
        [157,  50,   1]], dtype=uint8),
 array([[254, 157],
        [ 36,  50],
        [191,   1]], dtype=uint8))

# 브로드 캐스팅
차원이 다른 배열끼리 연산이 가능하게 해주는 것

In [113]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [114]:
a+5

array([ 5,  6,  7,  8,  9, 10])

In [115]:
a-2

array([-2, -1,  0,  1,  2,  3])

In [116]:
b = np.arange(6).reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [117]:
b*2

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [118]:
b>3

array([[False, False, False],
       [False,  True,  True]])

두 개의 배열을 연산할 경우
* Shape이 똑같은 배열끼리는 아무 문제 없다.
* 다른 경우, 둘 중 하나가 1차원이면서 배열의 열의 개수가 같아야 한다.

In [119]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [120]:
b = np.arange(3)
b

array([0, 1, 2])

In [121]:
a+b

array([[0, 2, 4],
       [3, 5, 7]])

In [122]:
c = np.arange(27).reshape(3,3,3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [123]:
c+b

array([[[ 0,  2,  4],
        [ 3,  5,  7],
        [ 6,  8, 10]],

       [[ 9, 11, 13],
        [12, 14, 16],
        [15, 17, 19]],

       [[18, 20, 22],
        [21, 23, 25],
        [24, 26, 28]]])

In [124]:
c*b

array([[[ 0,  1,  4],
        [ 0,  4, 10],
        [ 0,  7, 16]],

       [[ 0, 10, 22],
        [ 0, 13, 28],
        [ 0, 16, 34]],

       [[ 0, 19, 40],
        [ 0, 22, 46],
        [ 0, 25, 52]]])

In [125]:
d = np.arange(4)
a+d

ValueError: operands could not be broadcast together with shapes (2,3) (4,) 

In [126]:
e = np.arange(3).reshape(3,1)
e

array([[0],
       [1],
       [2]])

In [127]:
c+e

array([[[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10]],

       [[ 9, 10, 11],
        [13, 14, 15],
        [17, 18, 19]],

       [[18, 19, 20],
        [22, 23, 24],
        [26, 27, 28]]])

In [128]:
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

# 규칙
* 규칙 1: 두 배열의 차원 수가 다르면 더 작은 수의 차원을 가진 배열 shape의 앞쪽(왼쪽)을 1로 채운다.
* 규칙 2: 두 배열의 shape이 어떤 차원에서도 일치하지 않는다면 해당 차원의 shape이 1인 배열이 다른 shape과 일치하도록 늘어난다.
* 규칙 3: 임의의 차원에서 크기가 일치하지 않고 1도 아니라면 오류가 발생한다.

(2,3,4) + (1,3,4) --> (2,3,4)

(2,3,4) + (3,1) --> (1,3,1) --> (2,3,4)

(1,3,4) + (3,3,1) --> (3,3,4) + (3,3,4)

In [143]:
a = np.arange(42).reshape(2,3,7)
b = np. arange(7).reshape(1,7)
print(a.shape, b.shape)
a + b

(2, 3, 7) (1, 7)


array([[[ 0,  2,  4,  6,  8, 10, 12],
        [ 7,  9, 11, 13, 15, 17, 19],
        [14, 16, 18, 20, 22, 24, 26]],

       [[21, 23, 25, 27, 29, 31, 33],
        [28, 30, 32, 34, 36, 38, 40],
        [35, 37, 39, 41, 43, 45, 47]]])

In [144]:
a = np.arange(24).reshape(2,3,-1)
b = np.arange(12).reshape(3,4)
print(a.shape, b.shape)

(2, 3, 4) (3, 4)


In [145]:
a + b, (a+b).shape

(array([[[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]],
 
        [[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]]),
 (2, 3, 4))

In [146]:
c = np.arange(6).reshape(2,3,1) # --> (2,3,2)
c

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [147]:
d = np.arange(6).reshape(3,2) # --> (1,3,2) --> (2,3,2)
d

array([[0, 1],
       [2, 3],
       [4, 5]])

In [148]:
e = c + d
e.shape

(2, 3, 2)

In [149]:
e

array([[[ 0,  1],
        [ 3,  4],
        [ 6,  7]],

       [[ 3,  4],
        [ 6,  7],
        [ 9, 10]]])

### 인덱싱 슬라이싱

In [154]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [155]:
a[0][2]

2

In [156]:
a[1]

array([4, 5, 6, 7])

In [157]:
b = a[0:2, 1:3] # 파이썬에서 슬라이싱 하면 복사가 되지만, 넘파이는 레퍼런싱
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [158]:
b

array([[1, 2],
       [5, 6]])

In [159]:
b[0,0] = 100
b

array([[100,   2],
       [  5,   6]])

In [160]:
a

array([[  0, 100,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

# 팬시 인덱싱

In [1]:
a = np.arange(3, 8)
a

NameError: name 'np' is not defined

In [162]:
a[[1,3,4]]

array([4, 6, 7])

In [163]:
a[[True, False, True, False, True]]

array([3, 5, 7])

In [164]:
a > 5

array([False, False, False,  True,  True])

In [165]:
a[(a>5)]

array([6, 7])

In [166]:
a[(a>5)] = 1
a

array([3, 4, 5, 1, 1])

In [174]:
a = np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [168]:
a[3,4]

22

In [169]:
a[[3],[4]]

array([22])

In [170]:
a[[0,2],[2,3]]

array([ 2, 15])

In [5]:
b = np.arange(30).reshape(2,5,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [6]:
b[[0,1],[2,3],[1,2]]

array([ 7, 26])

In [7]:
b[[0,1,0,0,1], np.arange(5), np.random.randint(0,3,(5,))]

array([ 1, 20,  7, 10, 28])

### 병합과 분리

* hstack(arrays) : 수평으로 병합, arrays는 병합 대상 배열(튜플)
* vstack(arrays) : 수직으로 병합
* concatenate(array, axis = 0) : 지정한 축 기준으로 병합
* stack(arrays, axis = 0) : 

In [76]:
a = np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [77]:
b = np.arange(10,14).reshape(2,2)
b

array([[10, 11],
       [12, 13]])

In [12]:
np.vstack((a,b)) # 튜플 형태로 넣어줘야 한다.

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13]])

In [14]:
np.hstack((a,b))  # 영상처리 - 이미지 두 개를 가로로 연속으로 붙이고 싶을 때 쓰는 예

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13]])

In [18]:
np.concatenate((a,b), 0) # 0번째 축 기준. 맨 왼쪽에서부터. 차원은 오른쪽에서부터? // axis =  이건 써줘도 되고 안써줘도 된다
# vstack과 같고, 1을 쓰면 hstack과 같다

array([[ 0,  1],
       [ 2,  3],
       [10, 11],
       [12, 13]])

In [88]:
c = np.stack((a,b))
c

array([[[ 0,  1],
        [ 2,  3]],

       [[10, 11],
        [12, 13]]])

In [89]:
c.shape

(2, 2, 2)

In [84]:
c = np.stack((a,b), 0) # 0이면 첫 번째 축에 하나씩 들어간것
c

array([[[ 0,  1],
        [ 2,  3]],

       [[10, 11],
        [12, 13]]])

In [86]:
np.shape(c)

(2, 2, 2)

In [91]:
c = np.stack((a,b), 1) # 1이면 두 번째 축에 하나씩 들어간것.. 다시 정리해보자
c

array([[[ 0,  1],
        [10, 11]],

       [[ 2,  3],
        [12, 13]]])

In [82]:
np.shape(c)

(2, 2, 2)

### split
* 헷갈리지 않게 조심하자. vsplit hsplit!!

In [30]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
np.hsplit(a, 2)

[array([0, 1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10, 11])]

In [32]:
np.hsplit(a,3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [33]:
np.hsplit(a, 5) # 나누어 떨어지는 숫자로 해야함

ValueError: array split does not result in an equal division

In [34]:
np.hsplit(a, [2, 5]) # 인덱스 위치로 나누고 싶다!

[array([0, 1]), array([2, 3, 4]), array([ 5,  6,  7,  8,  9, 10, 11])]

In [93]:
b = np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
np.vsplit(b, 2)

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [38]:
np.hsplit(b, [2]) # 인덱스 2 위치에서 잘라주고 싶다! 0, 2, 4

[array([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]])]

In [94]:
np.split(b, 2, 0) # vsplit과 같이 될 것이다~

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]])]

In [109]:
np.split(b,1,1)

[array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])]

In [95]:
np.split(b, [2], 1)

[array([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]])]

In [111]:
np.split(b,[1,2],1)

[array([[0],
        [3],
        [6],
        [9]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]])]

In [42]:
np.split(b, 3, 1)

[array([[0],
        [3],
        [6],
        [9]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]])]

### 검색기능

* ret = numpy.where(condition [, t, f]) : 조건에 맞는 요소 찾기
  * ret : return된 배열(튜플)
  * condition : 조건식
  * t : 조건에 맞는 값에 지정할 값이나 배열(조건과 같은 shape)
  * f : 조건에 틀린 값에 지정할 값이나 배열
* numpy.nonzero(array) : array에서 요소 중 0이 아닌 요소의 인덱스들을 반환(튜플)
* numpy.all(array [, axis]) : array의 모든 요소가 True인지 검색
  * array : 검색 대상 배열
  * axis : 검색 기준 축. 생략 시 모든 요소, 지정시 축 개수별로 결과 반환
* numpy.any(array [, axis]) : array의 요소 중 하나라도 True가 있는지 검색

In [44]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
coords = np.where(a>6) # 조건에 해당하는 배열의 인덱스를 반환! 행값 열값 배열 따로!
coords

(array([1, 2, 2, 2, 2], dtype=int64), array([3, 0, 1, 2, 3], dtype=int64))

In [57]:
np.stack((coords[0], coords[1]), 1)
# 위 따로 나온 배열을 stack으로 합해서 좌표 정보를 얻을 수 있다

array([[1, 3],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3]], dtype=int64)

In [112]:
b = np.array([0,1,2,0,1,2])
np.nonzero(b)

(array([1, 2, 4, 5], dtype=int64),)

In [54]:
c = np.array([[0,1,2],[1,2,0],[2,0,1]])
c

array([[0, 1, 2],
       [1, 2, 0],
       [2, 0, 1]])

In [55]:
np.nonzero(c) # 행 인덱스 배열, 열 인덱스 배열을 반환

(array([0, 0, 1, 1, 2, 2], dtype=int64),
 array([1, 2, 0, 1, 0, 2], dtype=int64))

In [113]:
d = np.array([[[True, False, True, True], [True, True, False, True], [True, True, True, True]], [[True, True, True, True], [True, False, True, True], [True, True, True, True]]])
d

array([[[ True, False,  True,  True],
        [ True,  True, False,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True, False,  True,  True],
        [ True,  True,  True,  True]]])

In [114]:
d.shape

(2, 3, 4)

In [115]:
np.all(d)

False

In [116]:
np.all(d, 0) # 0번축은 두 그룹 비교

array([[ True, False,  True,  True],
       [ True, False, False,  True],
       [ True,  True,  True,  True]])

In [117]:
np.all(d, 1) # 1번축은 두 그룹의 세로끼리 비교

array([[ True, False, False,  True],
       [ True, False,  True,  True]])

In [118]:
np.all(d, 2) # 2번축은 가로 각 행

array([[False, False,  True],
       [ True, False,  True]])

In [69]:
np.any(d)

True

In [70]:
np.any(d, 1)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

### 통계함수
* sum(array [,axis]) : 배열의 합계
* mean 평균
* amin 최솟값 min()과 동일
* amax 최댓값 max()와 동일

In [119]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [120]:
np.sum(a)

66

In [121]:
np.sum(a,0)

array([12, 15, 18, 21])

In [122]:
np.mean(a)

5.5

In [123]:
np.mean(a, 0)

array([4., 5., 6., 7.])

In [74]:
np.amin(a,1)

array([0, 4, 8])